### PR TITLE
change package and package lock

### PR DESCRIPTION
**Pull request by wang-joseph**
Since this is a really important change I made an entirely new branch just for this important and critical and bug fixing change!!

### CODE REVIEW

**Comment by shari09** [comment]
nice rearrangement

**Comment by wang-joseph** [comment]
did u see how critical this pr was

**Review by shari09 — APPROVED** [review]
This is definitely the most important PR of our entire project. GOOD WORK!!!!!!! 😄

**Comment by wang-joseph** [comment]
aw you flatter me thank you very much

**Pull request merged**
